spring.application.name=userservice
spring.config.import=optional:application.secret.properties

server.port=8081

spring.jpa.hibernate.ddl-auto=update

USER_ALREADY_EXIST= User Already Exist.
USER_NOT_FOUND= User Not Found.
INVALID_CREDENTIALS= Invalid Credentials.
INVALID_ROLE= Invalid Role.
SERVER_ERROR= Server Error. Please try again later.